---
output: 
    stevetemplates::statement:
    latex_engine: pdflatex
geometry: margin=1in

title: "RWD pneumonic COPD exacerbation"
author: Akihiro Shiroshita
affiliation: Division of Epidemiology, Department of Medicine, Vanderbilt University School of Medicine
email: "akihiro.shiroshita@vanderbilt.edu"

fontfamily: cochineal
fontsize: 11pt
---

```{r set-up, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message = FALSE,
                      fig.pos="t", fig.height=4, out.extra="")

packages = c("devtools",
             "usethis",
             "here",
             "readr",
             "data.table",
             "readxl",
             "tidyverse",
             "R.utils",
             "tidylog",
             "lubridate",
             "comorbidity",
             "psych",
             "ggplot2",
             "ggplotgui",
             "ggthemes",
             "arsenal",
             "survival",
             "scales",
             "texreg",
             "kableExtra",
             "survminer",
             "MatchIt",
             "WeightIt",
             "cobalt",
             "boot")
package.check <- lapply(packages, FUN = function(x){
  if (!require(x, character.only = TRUE)){
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})

getwd()
rm(list=ls())

df <- read_rds("output/analysis_data.rds")

df_cc <- df %>% 
  select(age, sex, adm_adl, cci_score, spo2, ams, sbp, immunodef, dev_place, emp_abx,
         base_dialysis, inhosp_death, los, emp_steroid) %>% 
  drop_na() %>% 
  mutate(id = row_number())
```

# Complete case analysis  

```{r}
summary(tableby(emp_steroid ~ surv_obj, , data=df_cc))
```

### Unadjusted K-M curve  

```{r}
surv_obj <- Surv(df_cc$los, df_cc$inhosp_death)

fit_surv <- survfit(surv_obj ~ emp_steroid,
                    data = df_cc)
ggsurvplot(fit_surv)
```
### Cox regression  

```{r}
fit_cox <- coxph(surv_obj ~ emp_steroid + age + sex + adm_adl + cci_score + spo2 + ams + 
                   sbp + immunodef + dev_place + emp_abx + base_dialysis,
                 data = df_cc,
                 id = id)

summary(fit_cox)
```

### IPTW using entropy balancing  

Developed by Hainmueller et al.

```{r}
trt_form <- "emp_steroid ~ age + sex + adm_adl + cci_score + spo2 + ams + sbp + immunodef + dev_place +
             emp_abx + base_dialysis"

eb.out <- weightit(as.formula(trt_form),
                  data = df_cc,
                  method = "CBPS",
                  over = TRUE,
                  estimand = "ATE")

eb.out <- matchit(as.formula(trt_form),
                  data = as.data.frame(df_cc),
                  distance = "mahalanobis",
                  exact = c("emp_abx"),
                  replace = TRUE)

#eb.out <- weightit(as.formula(trt_form),
#                  data = df_cc,
#                  method = "ebal",
#                  moments = 3,
#                  estimand = "ATE")
```

### Balance check  

```{r}
summary(eb.out)
```

```{r}
love.plot(eb.out,
          binary = "std",
          continuous = "std",
          abs = TRUE,
          stats = c("m", "ks"),
          sd.denom = "treat",
          line = TRUE,
          var.order = "adj",
          theresholds = c(.10, .05))
```

### Doubly robust

### Weighted cox regression  
```{r}
fit_cox_weighted <- coxph(surv_obj ~ emp_steroid + age + sex + adm_adl + cci_score + spo2 + ams + 
                   sbp + immunodef + dev_place + emp_abx + base_dialysis,
                   weights = eb.out$weights,
                   data = df_cc,
                   id = id)

summary(fit_cox_weighted)
```

### Bootstrap resampling  
#### Standard error  

```{r}
est_fun <- function(data, index){
  
  out <- weightit(as.formula(trt_form),
                  data = data[index,],
                  method = "CBPS",
                  over = TRUE,
                  estimand = "ATE")
  
  fit_cox_weighted <- coxph(surv_obj ~ emp_steroid + age + sex + adm_adl + cci_score + spo2 + ams + 
                   sbp + immunodef + dev_place + emp_abx + base_dialysis,
                   weights = eb.out$weights,
                   data = data[index,],
                   id = id)
  
  return(fit_cox_weighted[["coefficients"]][["emp_steroid"]])
}

boot_out <- boot(est_fun,
                 data = df_cc,
                 R = 1000)

boot_out
```

#### Percentile confidence interval

```{r}
boot.ci(boot_out, type = "perc")
```

### Weighted K-M curve  

```{r}
fit_surv_weighted <- survfit(surv_obj ~ emp_steroid,
                             data = df_cc,
                             weights = eb.out$weights)
ggsurvplot(fit_surv_weighted)
```